In [1]:
pip install roboticstoolbox-python

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 12.9 MB 5.3 MB/s 
     |████████████████████████████████| 183 kB 48.0 MB/s 
     |████████████████████████████████| 112.2 MB 88 kB/s 
     |████████████████████████████████| 1.5 MB 46.0 MB/s 
     |████████████████████████████████| 13.5 MB 40.9 MB/s 
     |████████████████████████████████| 106 kB 64.4 MB/s 
  Created wheel for colored: filename=colored-1.4.4-py3-none-any.whl size=14268 sha256=df6928d2313326b18612d3f0636c4093709c8775b7e623442f1ca3363af6d8fb
  Stored in directory: /root/.cache/pip/wheels/2b/96/97/3ed201ace26d471cdec8a760a4b3cc406a29714c7637b0b336
  Created wheel for pgraph-python: filename=pgraph_python-0.6.1-py3-none-any.whl size=11482 sha256=90498db75d49cf5f8a61548f078e0c3deb4e73d32c637ab1cd93d8f3b4868213
  Stored in directory: /root/.cache/pip/wheels/0c/96/4a/6802f53d94902fa9431fe1d0ca769f5da8faee8894188c1fd5
  Created wheel for pr

In [6]:
from spatialmath import *
from spatialmath.base import *
import spatialmath.base.symbolic as sym
import numpy as np
from matplotlib import pyplot as plt

In [7]:
###1st question
a = sym.symbol('⍺')
b = sym.symbol('β') 
c = sym.symbol('𝛾')
rpy_matrix = np.matrix(rpy2r(a,b,c))
print(rpy_matrix)

[[cos(β)*cos(𝛾) sin(β)*sin(⍺)*cos(𝛾) - sin(𝛾)*cos(⍺)
  sin(β)*cos(⍺)*cos(𝛾) + sin(⍺)*sin(𝛾)]
 [sin(𝛾)*cos(β) sin(β)*sin(⍺)*sin(𝛾) + cos(⍺)*cos(𝛾)
  sin(β)*sin(𝛾)*cos(⍺) - sin(⍺)*cos(𝛾)]
 [-sin(β) sin(⍺)*cos(β) cos(β)*cos(⍺)]]


In [9]:
###2nd question
a = sym.symbol('⍺')
b = sym.symbol('β') 
c = sym.symbol('𝛾')

rpy_matrix = np.matrixrpy2r(a,-90,c,unit = 'deg')
print(rpy_matrix)

AttributeError: ignored

In [10]:
###3rd question
a = sym.symbol('⍺')
b = sym.symbol('β') 
c = sym.symbol('𝛾')

rpy_zyx = SO3.RPY(a,np.pi/2,c)
print(rpy_zyx)
print()
rpy_zyz = SO3.Rz(a)*SO3.Ry(np.pi/2)*SO3.Rz(c)
print(rpy_zyz)

  6.12323399573677e-17*cos(𝛾) 1.0*sin(⍺)*cos(𝛾) - 1.0*sin(𝛾)*cos(⍺) 1.0*sin(⍺)*sin(𝛾) + 1.0*cos(⍺)*cos(𝛾)  
  6.12323399573677e-17*sin(𝛾) 1.0*sin(⍺)*sin(𝛾) + 1.0*cos(⍺)*cos(𝛾) -1.0*sin(⍺)*cos(𝛾) + 1.0*sin(𝛾)*cos(⍺)  
  -1        6.12323399573677e-17*sin(⍺) 6.12323399573677e-17*cos(⍺)  


  -1.0*sin(⍺)*sin(𝛾) + 6.12323399573677e-17*cos(⍺)*cos(𝛾) -1.0*sin(⍺)*cos(𝛾) - 6.12323399573677e-17*sin(𝛾)*cos(⍺) 1.0*cos(⍺)    
  6.12323399573677e-17*sin(⍺)*cos(𝛾) + 1.0*sin(𝛾)*cos(⍺) -6.12323399573677e-17*sin(⍺)*sin(𝛾) + 1.0*cos(⍺)*cos(𝛾) 1.0*sin(⍺)    
  -1.0*cos(𝛾)  1.0*sin(𝛾)    0         



In [11]:
###7th question
x = sym.symbol('x')

rpy_matrix = np.matrix([[0.4,x,x],[0.138,x,x],[-0.906,0.224,0.358]])
print(rpy_matrix)
print()
tranform_matrix_2_rpy_angles = tr2rpy(rpy_matrix)
print(tranform_matrix_2_rpy_angles)
print()
new_rpy_matrix = rpy2r(tranform_matrix_2_rpy_angles)
print(new_rpy_matrix)

[[0.4 x x]
 [0.138 x x]
 [-0.906 0.224 0.358]]

[0.55910132 1.13386475 0.33221355]

[[ 0.400024    0.17783971  0.899085  ]
 [ 0.13800828  0.95811947 -0.25091989]
 [-0.90605436  0.22445515  0.35872743]]


In [12]:
###8th question
y = sym.symbol('y')
b = sym.symbol('β')
c = sym.symbol('𝛾')

R = np.matrix([[-0.82,y,0],[y,y,y],[y,y,-1]])
print(R)
print()
R1 = SO3.Rz(0,unit = 'deg')*SO3.Ry(b)*SO3.Rz(c)
print(R1)
rpy2r(0,3.14,0.609)

[[-0.82 y 0]
 [y y y]
 [y y -1]]

  1.0*cos(β)*cos(𝛾) -1.0*sin(𝛾)*cos(β) 1.0*sin(β)    
  1.0*sin(𝛾)   1.0*cos(𝛾)   0             
  -1.0*sin(β)*cos(𝛾) 1.0*sin(β)*sin(𝛾) 1.0*cos(β)    



array([[-8.20219435e-01, -5.72047526e-01,  1.30632653e-03],
       [-5.72046800e-01,  8.20220475e-01,  9.11073160e-04],
       [-1.59265292e-03,  0.00000000e+00, -9.99998732e-01]])

In [13]:
###9th question
R = np.matrix([[0.3333,0.9107,0.2440],
             [-0.2440,0.3333,0.9107],
             [-0.9107,0.2440,0.3333]])

[x,e] = np.linalg.eig(R)
print(x)
print()
print(e)
print()
axis_angle = math.acos((np.trace(R) - 1)/2)
print(axis_angle)
print()
q = UnitQuaternion(rpy2r(axis_angle,axis_angle,axis_angle))
print(q)

[ 0.75125533+0.86386965j  0.75125533-0.86386965j -0.50261066+0.j        ]

[[ 0.63276418+0.j          0.63276418-0.j          0.45217565+0.j        ]
 [ 0.32259785+0.46149244j  0.32259785-0.46149244j -0.59344164+0.j        ]
 [-0.12017499+0.51780577j -0.12017499-0.51780577j  0.66585599+0.j        ]]



NameError: ignored