In [1]:
pip install roboticstoolbox-python

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 12.9 MB 12.3 MB/s 
     |████████████████████████████████| 1.5 MB 61.1 MB/s 
     |████████████████████████████████| 13.5 MB 57.5 MB/s 
     |████████████████████████████████| 112.2 MB 1.1 MB/s 
     |████████████████████████████████| 183 kB 64.5 MB/s 
     |████████████████████████████████| 106 kB 89.1 MB/s 
  Created wheel for colored: filename=colored-1.4.4-py3-none-any.whl size=14268 sha256=23405e261dea575515f050096e6ac4b3a13a8db32dbdde3670b2306ec8e9e8ff
  Stored in directory: /root/.cache/pip/wheels/2b/96/97/3ed201ace26d471cdec8a760a4b3cc406a29714c7637b0b336
  Created wheel for pgraph-python: filename=pgraph_python-0.6.1-py3-none-any.whl size=11482 sha256=76846666e11bc35d365d67ae62b6c2f2e115755f66062b50da309cfcda74d337
  Stored in directory: /root/.cache/pip/wheels/0c/96/4a/6802f53d94902fa9431fe1d0ca769f5da8faee8894188c1fd5
  Created wheel for 

In [4]:
from spatialmath import *
from spatialmath.base import *
import spatialmath.base.symbolic as sym
import numpy as np
from matplotlib import pyplot as plt

In [20]:
## 1st question
a = rotx(30,'deg')
b = rotz(45,'deg')
c = b@a
d = np.matrix([[-5, 5, 5]])
e = (d.T)
print(a)
print()
print(b)
print()
print(c)
print()
print(e)
print()
print(c@e)

[[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]

[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]

[[ 0.70710678 -0.61237244  0.35355339]
 [ 0.70710678  0.61237244 -0.35355339]
 [ 0.          0.5         0.8660254 ]]

[[-5]
 [ 5]
 [ 5]]

[[-4.82962913]
 [-2.24143868]
 [ 6.83012702]]


In [16]:
### 2nd Question
u = roty(30,'deg')
v = rotx(30,'deg')
w = v@u
k = np.matrix([3,5,3])
l = (k.T)
m = np.linalg.inv(w)
b = m@l
print(u)
print()
print(v)
print()
print(w)
print()
print(l)
print()
print(m)
print()
print(b)

[[ 0.8660254  0.         0.5      ]
 [ 0.         1.         0.       ]
 [-0.5        0.         0.8660254]]

[[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]

[[ 0.8660254  0.         0.5      ]
 [ 0.25       0.8660254 -0.4330127]
 [-0.4330127  0.5        0.75     ]]

[[3]
 [5]
 [3]]

[[ 0.8660254  0.25      -0.4330127]
 [ 0.         0.8660254  0.5      ]
 [ 0.5       -0.4330127  0.75     ]]

[[2.54903811]
 [5.83012702]
 [1.58493649]]


In [17]:
##3rd question
u = rotx(45,'deg')
v = rotz(60,'deg')
w = u@v
k = np.matrix([-10,10,10])
l = (k.T)
m = np.linalg.inv(w)
b = m@l
print(u)
print()
print(v)
print()
print(w)
print()
print(l)
print()
print(m)
print()
print(b)

[[ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]
 [ 0.          0.70710678  0.70710678]]

[[ 0.5       -0.8660254  0.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]

[[ 0.5        -0.8660254   0.        ]
 [ 0.61237244  0.35355339 -0.70710678]
 [ 0.61237244  0.35355339  0.70710678]]

[[-10]
 [ 10]
 [ 10]]

[[ 0.5         0.61237244  0.61237244]
 [-0.8660254   0.35355339  0.35355339]
 [ 0.         -0.70710678  0.70710678]]

[[7.24744871e+00]
 [1.57313218e+01]
 [8.88178420e-16]]


In [18]:
### 4th Question
u = rotz(60,'deg')
v = rotx(30,'deg')
w = u@v
k = np.matrix([4,4,3])
l = (k.T)
m = np.linalg.inv(w)
b = m@l
print(u)
print()
print(v)
print()
print(w)
print()
print(l)
print()
print(m)
print()
print(b)

[[ 0.5       -0.8660254  0.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]

[[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]

[[ 0.5       -0.75       0.4330127]
 [ 0.8660254  0.4330127 -0.25     ]
 [ 0.         0.5        0.8660254]]

[[4]
 [4]
 [3]]

[[ 0.5        0.8660254  0.       ]
 [-0.75       0.4330127  0.5      ]
 [ 0.4330127 -0.25       0.8660254]]

[[5.46410162]
 [0.23205081]
 [3.33012702]]


In [6]:
#5th question
R1 = SO3.Rx(45,'deg')
R2 = SO3.Ry(60,'deg')
R3 = SO3.Rz(30,'deg')
R = R1*R2*R3    #rotation matrix
print('Rotation matrix is : \n',R)
R1 = SE3.Rx(45,'deg')*SE3.Ry(60,'deg')*SE3.Rz(30,'deg')
q = SE3(-3,3,6) # translated vector
#TRANSFORMATION MATRIX
T = q*R1
print('homogeneous transformation matrix is:\n',T)
Rinv = np.linalg.inv(R1)
qinv = np.linalg.inv(q)
Tinv = Rinv@qinv
print('inverse homogeneous transformation matrix is:\n',Tinv)

Rotation matrix is : 
    0.433    -0.25      0.866     
   0.8839    0.3062   -0.3536    
  -0.1768    0.9186    0.3536    

homogeneous transformation matrix is:
    0.433    -0.25      0.866    -3         
   0.8839    0.3062   -0.3536    3         
  -0.1768    0.9186    0.3536    6         
   0         0         0         1         

inverse homogeneous transformation matrix is:
 [[ 0.4330127   0.88388348 -0.1767767  -0.29195215]
 [-0.25        0.30618622  0.91855865 -7.17991057]
 [ 0.8660254  -0.35355339  0.35355339  1.53741604]
 [ 0.          0.          0.          1.        ]]


In [7]:
#question 6
R3 = SO3.Ry(60,'deg')
R2 = SO3.Rz(45,'deg')
R1 = SO3.Ry(30,'deg')
R = R3@R2@R1
print(R)
R1 = SE3.Ry(60,'deg')*SE3.Rz(45,'deg')*SE3.Ry(30,'deg')
q = SE3(1,2,-3)
T = q*R1
print('homogeneous transformation matrix is:\n',T)
pb = np.array([[1, 2, 1,]])
pbtrans = (pb.transpose())
d = T*pbtrans
print(d)

  -0.1268   -0.3536    0.9268    
   0.6124    0.7071    0.3536    
  -0.7803    0.6124    0.1268    

homogeneous transformation matrix is:
   -0.1268   -0.3536    0.9268    1         
   0.6124    0.7071    0.3536    2         
  -0.7803    0.6124    0.1268   -3         
   0         0         0         1         

[[ 1.09284343]
 [ 4.38013939]
 [-2.42875873]]


In [8]:
#question 7:
R2 = SO3.Rz(45,'deg')
R1 = SO3.Rx(90,'deg')
R = R2@R1
print('Rotation matrix is:\n',R) # Rotation matrix
R1 = SE3.Rz(45,'deg')*SE3.Rx(90,'deg')
q = SE3([2,3,1])  # translated vector
qinv = np.linalg.inv(q)
rinv = np.linalg.inv(R1)
tinv = SE3(rinv@qinv)
print('inverse homogeneous matix\n',tinv)
pa = np.array([2,2,3]) # Point P wrt frame A
at = pa.transpose()
pb = at*tinv   
print('point p wrt to local coordinate:\n',pb)

Rotation matrix is:
    0.7071    0         0.7071    
   0.7071    0        -0.7071    
   0         1         0         

inverse homogeneous matix
    0.7071    0.7071    0        -3.536     
   0         0         1        -1         
   0.7071   -0.7071    0         0.7071    
   0         0         0         1         

point p wrt to local coordinate:
 [[-0.70710678]
 [ 2.        ]
 [ 0.70710678]]


In [9]:
# Question8:
R1 = SE3.Ry(60,'deg')
R2 = SE3.Rz(30,'deg')
R = R1@R2
print(R)
q = SE3([-3,3,-1])
qinv = np.linalg.inv(q)
rinv = np.linalg.inv(R)
tinv = SE3(rinv@qinv)
pa = np.array([2,2,1])
pat = pa.transpose()
pb = pat*tinv
print(pb)

   0.433    -0.25      0.866     0         
   0.5       0.866     0         0         
  -0.75      0.433     0.5       0         
   0         0         0         1         

[[ 0.16506351]
 [-1.25      ]
 [ 5.33012702]]


In [10]:
#question9:
R = rot2(45,'deg')
print(R)
c = np.linalg.eig(R)
print(c)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
(array([0.70710678+0.70710678j, 0.70710678-0.70710678j]), array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]]))


In [19]:
### 10th question
b = rotx(30,'deg')
print(b)
d,v = np.linalg.eig(b)
print(d)

[[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]
[0.8660254+0.5j 0.8660254-0.5j 1.       +0.j ]
